project_id = "nspooysfhhkybdrlhmhd"

[functions.scan-item]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.generate-ai-notifications]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false
